import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import Header from "./components/Header";
import Footer from "./components/Footer";
import ConditionalHero from "./components/ConditionalHero";
import SessionProviderWrapper from "./providers/SessionProviderWrapper";
import AnimatedSection from "./components/AnimatedSection";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <SessionProviderWrapper>
          {/* ✅ Optional: Animate header and hero */}
          <Header />
          <ConditionalHero />
          {/* ✅ Animate page content */}
          <main>
            <AnimatedSection>{children}</AnimatedSection>
          </main>
          {/* ✅ Optional: Animate footer */}
          <AnimatedSection>
            <Footer />
          </AnimatedSection>
        </SessionProviderWrapper>
      </body>
    </html>
  );
}
